# Generated by Django 2.2.12 on 2020-04-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unidadeorganizacional',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_unidadeorganizacional_nome'),
        ),
    ]
