# Generated by Django 2.2.12 on 2020-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200418_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Modalidade',
                'verbose_name_plural': 'Tipos de Modalidades',
            },
        ),
        migrations.AddConstraint(
            model_name='tipomodalidade',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_tipomodalidade_nome'),
        ),
    ]
