# Generated by Django 2.2.12 on 2020-04-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[['I', 'Individual'], ['C', 'Coletivo']], max_length=1)),
                ('tipo_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoModalidade')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
    ]
