# Generated by Django 2.2.12 on 2020-04-22 15:27

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', stdimage.models.StdImageField(upload_to='atletas')),
                ('cpf', models.CharField(max_length=13)),
                ('rg', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(choices=[['M', 'Masculino'], ['F', 'Femenino']], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('tipo_sanguineo', models.CharField(max_length=3)),
                ('plano_saude', models.CharField(max_length=200)),
                ('numero_carteira_sus', models.CharField(max_length=20)),
                ('medicamento', models.TextField()),
                ('alergia', models.TextField()),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tipomodalidade',
            name='unique_tipomodalidade_nome',
        ),
        migrations.RemoveConstraint(
            model_name='unidadeorganizacional',
            name='unique_unidadeorganizacional_nome',
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='tipo_modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoModalidade', verbose_name='Tipo de Modalidade'),
        ),
        migrations.AlterField(
            model_name='tipomodalidade',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadeorganizacional',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
