# Generated by Django 2.2.12 on 2020-04-22 15:42

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200422_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='atleta',
            name='medicamento_controlado',
            field=models.TextField(blank=True, verbose_name='Medicamento Controlado'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='alergia',
            field=models.TextField(blank=True, verbose_name='Alergia'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, upload_to='atletas'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='genero',
            field=models.CharField(choices=[['M', 'Masculino'], ['F', 'Femenino']], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='numero_carteira_sus',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nº Carteira do SUS'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='plano_saude',
            field=models.CharField(blank=True, max_length=200, verbose_name='Plano de Saúde'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='rg',
            field=models.CharField(max_length=50, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
    ]
