# Generated by Django 2.2.12 on 2020-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200422_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
