# Generated by Django 2.2.12 on 2020-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200422_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
