# Generated by Django 2.2.12 on 2020-04-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200422_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaPorModalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotacao_permitida', models.IntegerField(verbose_name='Lotação Permitida')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Modalidade', verbose_name='Modalidade')),
            ],
            options={
                'verbose_name': 'Atleta Por Modalidade',
                'verbose_name_plural': 'Atletas por Modalidade',
                'unique_together': {('modalidade', 'lotacao_permitida')},
            },
        ),
    ]
