# Generated by Django 2.2.12 on 2020-04-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_atletapormodalidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atletapormodalidade',
            options={'verbose_name': 'Atleta por Modalidade', 'verbose_name_plural': 'Atletas por Modalidade'},
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atleta', verbose_name='Atleta')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Modalidade', verbose_name='Modalidade')),
                ('unidade_organizacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnidadeOrganizacional', verbose_name='Unidade Organizacional')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
