# Generated by Django 2.2.12 on 2020-04-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200422_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('modalidade', 'atleta', 'unidade_organizacional')},
        ),
    ]
